### ISSUE TITLE
ERROR Unable to connect to the database in Kubernetes

### ISSUE THREAD

**Issue by pamanseau** [subquery/network-indexer-services#527]
When deploying in Kubernetes the application indexer-coordinator is not connecting to Postgres.

With `NODE_ENV=local`, the connection works, but then it tries to connect to the docker.sock and terminates.
With `NODE_ENV=production` the error `Unable to connect to the database`

Tested with either the ENV variables or command arguments

```yaml
DB_HOST: graph.postgres
DB_NAME: coordinator
DB_USERNAME: postgres
DB_PASSWORD: xxx-xxx-xxx-xxx
DB_PORT: 5432
LOG_LEVEL: debug
NODE_ENV: production
```

```yaml
          command: [ "node", "dist/main.js" ]
          args:
            - --network-endpoint=https://mainnet.base.org
            - --network=mainnet
            - --postgres-host=graph.postgres
            - --postgres-database=coordinator
            - --postgres-username=postgres
            - --postgres-password=xxx-xxx-xxx-xxx
            - --postgres-port=5432
            - --postgres-ssl-mode=disabled
            - --port=8000
            - --start-port=3100
            - --secret-key=287sjsd928aD2
            - --ipfs=https://unauthipfs.subquery.network/ipfs/api/v0
```
